spring:
  datasource:
    hikari:
      master:
        jdbc-url:
        username: username
        password: password
        driver-class-name: com.mysql.cj.jdbc.Driver
      slave:
        jdbc-url:
        username: username
        password: password
        driver-class-name: com.mysql.cj.jdbc.Driver